repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
- repo: https://github.com/hmcts/cpp-hooks-pre-commit-terraform
  rev: main
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/hmcts/cpp-hooks-gitleaks
  rev: main
  hooks:
    - id: gitleaks
