name: CPP AKS Module
trigger: none
pr:
  - main

parameters:
  - name: tfversion
    default: 1.3.10

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'

stages:
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - stage: precommit
    pool:
      name: "MDV-ADO-AGENTS-01"
    jobs:
    - job: precommit
      steps:
      - template: steps/terraform/terraform-precommit.yaml@cppAzureDevOpsTemplates
        parameters:
          tfversion: ${{ parameters.tfversion }}
