---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: "istio-ingress"
data:
  token: ${vault_token}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: "istio-ingress"
spec:
  vault:
    path: ${vault_path}
    server: ${vault_url}
    caBundle: ${ca_bundle}
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-mgmt-cert
  namespace: "istio-ingress"
spec:
  commonName: "${istio_ingress_mgmt_domain}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - "${istio_ingress_mgmt_domain}"
  issuerRef:
    kind: Issuer
    name: vault-issuer
  secretName: ${istio_gateway_mgmt_cert_secret_name}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-apps-cert
  namespace: "istio-ingress"
spec:
  commonName: "${istio_ingress_apps_domain}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - "${istio_ingress_apps_domain}"
  issuerRef:
    kind: Issuer
    name: vault-issuer
  secretName: ${istio_gateway_apps_cert_secret_name}