---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: "cert-manager"
data:
  token: ${vault_token}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: ${vault_path}
    server: ${vault_url}
    caBundle: ${ca_bundle}
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-mgmt-cert
  namespace: "istio-ingress-mgmt"
spec:
  commonName: "${element(istio_ingress_mgmt_domains, 0)}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    %{~ for dnsname in istio_ingress_mgmt_domains ~}
    - "${dnsname}"
    %{~ endfor ~}
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  secretName: ${istio_gateway_mgmt_cert_secret_name}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-apps-cert
  namespace: "istio-ingress"
spec:
  commonName: "${element(istio_ingress_apps_domains, 0)}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    %{~ for dnsname in istio_ingress_apps_domains ~}
    - "${dnsname}"
    %{~ endfor ~}
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  secretName: ${istio_gateway_apps_cert_secret_name}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-web-cert
  namespace: "istio-ingress-web"
spec:
  commonName: "${element(istio_ingress_web_domains, 0)}"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    %{~ for dnsname in istio_ingress_web_domains ~}
    - "${dnsname}"
    %{~ endfor ~}
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  secretName: ${istio_gateway_web_cert_secret_name}
