---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  profile: default
  hub: ${docker_registry}
  tag: ${docker_tag}
  values:
    gateways:                                                                                                            
      istio-ingressgateway:                                                                                                                                                                                  
        name: istio-ingressgateway                                                                                       
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-resource-group: ${istio_ingress_load_balancer_resource_group}
        service:
          type: LoadBalancer
        hpaSpec:
          minReplicas: ${hpa_min_replicas}
          maxReplicas: ${hpa_max_replicas}
    pilot:
      k8s:
        tolerations:
          - key: ${systempool_taint_key}
            operator: "Exists"
            effect: "NoSchedule"
        hpaSpec:
          minReplicas: ${hpa_min_replicas}
          maxReplicas: ${hpa_max_replicas}