---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-info
  namespace: ${namespace}
data:
  oidc_url: "${oidc_issuer_url}"
  subscription_id: "${subscription_id}"
  tenant_id: "${tenant_id}"
  mi_resource_group: "${mi_resource_group}"
  cluster_name: "${cluster_name}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: role-definition
  namespace: ${namespace}
data:
  ${role_definitions}
