%{~ for namespaces in system_namespaces ~}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-from-other-namespaces
  namespace: ${namespaces}
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-namespaces
  namespace: ${namespaces}
spec:
  podSelector: {}
  ingress:
    - from:
      %{~ for ns in namespace ~}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ${ns}
      %{~ endfor ~}
  policyTypes:
    - Ingress
---
%{~ endfor ~}
