instance:
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  kustomize:
    patches:
      - target:
          kind: Deployment
        patch: |
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: add
            path: /spec/template/spec/tolerations
            value:
              - key: "CriticalAddonsOnly"
                operator: "Exists"

      %{~ if lookup(workload_identity_client_ids, "source", null) != null ~}
      - target:
          kind: ServiceAccount
          name: source-controller
        patch: |
          
          - op: add
            path: /metadata/annotations/azure.workload.identity~1client-id
            value: "${lookup(workload_identity_client_ids, "source", "")}"
          
          - op: add
            path: /metadata/labels/azure.workload.identity~1use
            value: "true"
      %{~ endif ~}

      - target:
          kind: Deployment
          name: source-controller
        patch: |
          - op: add
            path: /metadata/labels/azure.workload.identity~1use
            value: "true"
          - op: add
            path: /spec/template/metadata/labels/azure.workload.identity~1use
            value: "true"

      %{~ if lookup(workload_identity_client_ids, "image_reflector", null) != null ~}
      - target:
          kind: ServiceAccount
          name: image-reflector-controller
        patch: |
          - op: add
            path: /metadata/annotations/azure.workload.identity~1client-id
            value: "${lookup(workload_identity_client_ids, "image_reflector", "")}"
          - op: add
            path: /metadata/labels/azure.workload.identity~1use
            value: "true"
      %{~ endif ~}
